version: "3.3"

services:
  nestar-api:
    container_name: nestar-api
    restart: always       # xatolik bersa qayta restart beradi.
    image: node:20.10.0
    ports:
      - 4001:3008
    volumes:
      - ./:/usr/src/nestar
    working_dir: /usr/src/nestar

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"


  nestar-batch:
    container_name: nestar-batch
    restart: unless-stopped       # xatolik bersa qayta restart beradi.
    image: node:20.10.0
    ports:
      - 4002:3009
    volumes:
      - ./:/usr/src/nestar
    working_dir: /usr/src/nestar

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge



# nestar-next:  localhost:4000 => container:3000
# nestar-api:   localhost:4001 => container:3007
# nestar-batch: localhost:4002 => container:3008
